from PyQt5 import QtCore,QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pixelMap = QtWidgets.QLabel(self.centralwidget)
        self.pixelMap.setGeometry(QtCore.QRect(0, 0, 561, 561))
        self.pixelMap.setText("")
        self.pixelMap.setObjectName("pixelMap")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 50, 191, 231))
        self.groupBox.setObjectName("groupBox")
        self.cameraMap = QtWidgets.QLabel(self.groupBox)
        self.cameraMap.setGeometry(QtCore.QRect(10, 20, 171, 171))
        self.cameraMap.setText("")
        self.cameraMap.setObjectName("cameraMap")
        self.btnCorrect = QtWidgets.QPushButton(self.groupBox)
        self.btnCorrect.setGeometry(QtCore.QRect(10, 200, 81, 32))
        self.btnCorrect.setObjectName("btnCorrect")
        self.btnCorrectCom = QtWidgets.QPushButton(self.groupBox)
        self.btnCorrectCom.setGeometry(QtCore.QRect(100, 200, 81, 32))
        self.btnCorrectCom.setObjectName("btnCorrectCom")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 280, 191, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 230, 171, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.btnStartImaging = QtWidgets.QPushButton(self.groupBox_2)
        self.btnStartImaging.setGeometry(QtCore.QRect(10, 250, 81, 32))
        self.btnStartImaging.setObjectName("btnStartImaging")
        self.btnImagingCom = QtWidgets.QPushButton(self.groupBox_2)
        self.btnImagingCom.setGeometry(QtCore.QRect(100, 250, 81, 32))
        self.btnImagingCom.setObjectName("btnImagingCom")
        self.resultMap = QtWidgets.QLabel(self.groupBox_2)
        self.resultMap.setGeometry(QtCore.QRect(10, 30, 171, 171))
        self.resultMap.setText("")
        self.resultMap.setObjectName("resultMap")
        self.simpleTimes = QtWidgets.QLineEdit(self.groupBox_2)
        self.simpleTimes.setGeometry(QtCore.QRect(70, 210, 111, 21))
        self.simpleTimes.setObjectName("simpleTimes")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 210, 58, 21))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 0, 191, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.labelNotice = QtWidgets.QLabel(self.groupBox_3)
        self.labelNotice.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.labelNotice.setText("")
        self.labelNotice.setObjectName("labelNotice")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ghost imaging demonstration system"))
        self.groupBox.setTitle(_translate("MainWindow", "Adjusting the camera position"))
        self.btnCorrect.setText(_translate("MainWindow", "Adjust"))
        self.btnCorrectCom.setText(_translate("MainWindow", "Done"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Imaging results"))
        self.btnStartImaging.setText(_translate("MainWindow", "Start"))
        self.btnImagingCom.setText(_translate("MainWindow", "Finish"))
        self.label.setText(_translate("MainWindow", "Sampling numbers："))
        self.groupBox_3.setTitle(_translate("MainWindow", "Status"))